#lang racket/base

(provide (prefix-out format: (all-defined-out)))

(define min-pos-fixint #x00)
(define max-pos-fixint #x7F)
(define min-fixmap #x80)
(define max-fixmap #x8F)
(define min-fixarray #x90)
(define max-fixarray #x9F)
(define min-fixstr #xA0)
(define max-fixstr #xBF)
(define nil #xC0)
(define unused #xC1)
(define false #xC2)
(define true #xC3)
(define bin8 #xC4)
(define bin16 #xC5)
(define bin32 #xC6)
(define ext8 #xC7)
(define ext16 #xC8)
(define ext32 #xC9)
(define float32 #xCA)
(define float64 #xCB)
(define uint8 #xCC)
(define uint16 #xCD)
(define uint32 #xCE)
(define uint64 #xCF)
(define int8 #xD0)
(define int16 #xD1)
(define int32 #xD2)
(define int64 #xD3)
(define fixext1 #xD4)
(define fixext2 #xD5)
(define fixext4 #xD6)
(define fixext8 #xD7)
(define fixext16 #xD8)
(define str8 #xD9)
(define str16 #xDA)
(define str32 #xDB)
(define array16 #xDC)
(define array32 #xDD)
(define map16 #xDE)
(define map32 #xDF)
(define min-neg-fixint #xE0)
(define max-neg-fixint #xFF)
